### ISSUE TITLE
The library contains built-in Typescript declarations, it's not marked with TS on Directory

### ISSUE THREAD

**Issue by RakaDoank** [react-native-community/directory#1286]
Hi, thanks for adding my library, even it's currently hottest trending when i wrote this issue.

[My library](https://reactnative.directory/?search=react-native-ping-android) is not marked with `[TS] Typescript Types`, even the library contains built-in TS declarations. Meanwhile, [my other library](https://reactnative.directory/?search=react-native-android-finish) is correctly marked with the `[TS] Typescript Types`.

Is this because the `githubUrl` i added to the `react-native-libraries.json` ([this commit](https://github.com/react-native-community/directory/pull/1273/commits/b5d5e1b7450a1889d7b5689e5af9a5f9c8ccdb71)) using the repository url (homepage) instead of the literally `library/package` itself (such as https://github.com/RakaDoank/react-native-ping-android/tree/main/package)? If it's true, i might create a new PR. Otherwise, any alternatives that i can follow?

**Comment by Simek** [comment]
Hello @RakaDoank, you have correctly identified the problem. You repository is setup as monorepo, and in those cases `githubUrl` need to point to the directory where `package.json` for the library resides. 

Feel free to create a PR correcting that, this should resolve the missing TS types flag.
