### ISSUE TITLE
react-native-pager-view should not include `web` compatibility

### ISSUE THREAD

**Issue by iggith** [react-native-community/directory#1316]
I've noticed an inconsistency regarding `react-native-pager-view`. 

It  [is listed](https://reactnative.directory/?search=react-native-pager-view) as compatible with `web`, but a team member from the `callstack` that maintains the library wrote last week that the `web` platform is not supported https://github.com/callstack/react-native-pager-view/issues/883#issuecomment-2395067152

**Comment by Simek** [comment]
Thank you for the report and providing the context! 👍

**Comment by iggith** [comment]
Thank you for an express fix :1st_place_medal:
