### ISSUE TITLE
Some libraries does not show on the website

### ISSUE THREAD

**Issue by f0wu5u** [react-native-community/directory#1322]
Eg `intercom-react-native` is added in the libraries json file

![image](https://github.com/user-attachments/assets/015c6c51-1a2c-491b-9201-ced289be7382)

but does not show on the results on the website

![image](https://github.com/user-attachments/assets/ede88ce4-3cec-4c4d-9bda-94cbe9acfbcb)

**Comment by Simek** [comment]
Thanks for the report @f0wu5u! 👍 

We recently added a mechanism which should prevent this situation from happening, but by mistake, I have commited the debug state of the code. With the mentioned PR shipped, the situation should be back to normal, sorry for the inconvenience.
