### ISSUE TITLE
Field 'Is project maintaining'

### ISSUE THREAD

**Issue by SilencerWeb** [react-native-community/directory#137]
There are projects that are not maintaining anymore and I think it would be amazing to add field 'is project maintaining' for warning people who would like to use them.

For example, [react-native-swipeout](https://github.com/dancormier/react-native-swipeout), it is not maintaining and maintainers will not help to resolve any issues, so you have to use it at one's own risk.

**Comment by jonsamp** [comment]
It is now possible to add an `unmaintained` key in **react-native-libraries.json**. This is not documented yet in **README.md**. I will add it there. Closing this issue.
