### ISSUE TITLE
react-native-location, don't work with Expo.

### ISSUE THREAD

**Issue by giautm** [react-native-community/directory#22]
I don't think that module can work with Expo, because it has native implement required `react-native link`
https://github.com/timfpark/react-native-location#react-native-link-installation

**Comment by jimmylee** [comment]
@giautm thanks for letting us know! Have you tested this yourself?

**Comment by brentvatne** [comment]
the expo key is intended to not just say whether something is compatible or not but also suggest an alternative. for example, with react-native-location, it should link to https://docs.expo.io/versions/latest/sdk/location.html rather than just be `true`

**Comment by jonsamp** [comment]
This issue seems resolved, so going to close. Please reopen an issue if you still think this persists.
