### ISSUE TITLE
Create a guide on creating a React Native package

### ISSUE THREAD

**Issue by jonsamp** [react-native-community/directory#250]
# Feature Request

It would be great to show developers using packages how they could develop and maintain their own packages.

## Possible implementation

- Create a new page (with next pages/routes) that displays information about how to create your own package.
  - Include creating packages for different platforms and native dependencies.
  - Include how to create a package that others can use easily.

**Comment by kpose** [comment]
Will be happy to send in a PR

**Comment by asklar** [comment]
> # Feature Request
> It would be great to show developers using packages how they could develop and maintain their own packages.
> 
> ## Possible implementation
> * Create a new page (with next pages/routes) that displays information about how to create your own package.
>   
>   * Include creating packages for different platforms and native dependencies.
>   * Include how to create a package that others can use easily.

that's dependent on the target platform though. Here's how you can do so for react-native-windows as an example: https://microsoft.github.io/react-native-windows/docs/native-modules

**Comment by jonsamp** [comment]
Just going through my old issues. This one is very old so closing it out. If someone wants to bring this back, feel free to!
