### ISSUE TITLE
Add all repositories from react-native-community

### ISSUE THREAD

**Issue by brentvatne** [react-native-community/directory#255]
@TheSavior pointed out that react-native-camera wasn't listed here. We should go over the libraries on react-native-community and add them here!

**Comment by rborn** [comment]
@kelset I can help with this (already started to make a list) 
How do you prefer to do it? One big PR or each package with it's own PR ? 

😻

**Comment by brentvatne** [comment]
we've added a bunch of them already but please go ahead and open a big pr with all of the ones that we are missing! ❤️

**Comment by rborn** [comment]
@brentvatne yeah, going one by one and check if it exits or is duplicated 🐌

**Comment by brentvatne** [comment]
thanks @rborn! i merged #291 so we can close this issue now i think.
