### ISSUE TITLE
Allow users to change the sort direction

### ISSUE THREAD

**Issue by luism3861** [react-native-community/directory#476]
this issue it's related with Dropdown style  in `iPhone SE(2nd generation)`  when you try to click `Sort Button` you cannot click this button.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/36824170/95628499-c63e7280-0a43-11eb-907c-969283d0c952.png)

**Comment by Simek** [comment]
Hi @luism3861, unfortunately even on desktop you cannot currently change the sort direction. 

There is no button for that and the direction is always set [manually ](https://github.com/react-native-community/directory/blob/master/pages/api/libraries/index.ts#L12)for the website requests. Currently even API do not support changing the sort direction, and all sorting operation happens in [sorting utils](https://github.com/react-native-community/directory/blob/master/util/sorting.js ).

But overall I think that this could be a nice feature request for the website and API.

**Comment by Simek** [comment]
Closing as done, since we allow to change the sort direction by pressing the button on the left from "Sort" select. Thanks @luism3861 for this idea! 🙏
