### ISSUE TITLE
I want my SDK to be compatible with Expo Managed Flow. Who shall we contact to go through the certification process?

### ISSUE THREAD

**Issue by KerenWex** [react-native-community/directory#522]
Hi,
Pendo is selling a platform, part of which is native iOS and Android SDKs. 
As part of this platform we have a new solution for React Native applications built from a combination of a Javascript agent and our native SDKs. This works fine with the bare workflow but we are getting requests from customers to have this work through the managed workflow. 
Who should we contact and what do we need to do in order to have our SDKs and agent certified by EXPO so that our customers will be able to install us through the managed workflow?
Thanks a lot
Keren Wexler
Sr. Director of Product, Pendo

**Comment by brentvatne** [comment]
hi :) we spoke over email, so closing this

**Comment by anthlasserre** [comment]
Hey guys @KerenWex @brentvatne I know it's been a while since your last messages. But I'm almost experimenting the same issue by trying to make **[@adyen/react-native](https://github.com/Adyen/adyen-react-native)** compatible with Expo as well. Any output on your last conversation ?
