### ISSUE TITLE
Move primary branch from master to main

### ISSUE THREAD

**Issue by brentvatne** [react-native-community/directory#535]

**Comment by darkworks** [comment]
somebody add this libary to director : https://github.com/flyskywhy/react-native-gcanvas

**Comment by Simek** [comment]
@darkworks Please next time prepare the PR or at least create separate issue. 

If you won't be able to push a PR, I will add the package later today.🙂

**Comment by darkworks** [comment]
ok @Simek created pull request 

thanks
