### ISSUE TITLE
libraries json schema doesn't allow url params in images

### ISSUE THREAD

**Issue by asklar** [react-native-community/directory#551]
```
    "images": ["https://github.com/asklar/react-native-xaml/blob/main/example/rnx.gif?raw=true"],
```

produces a CI error because of the `?raw=true` bit at the end

**Comment by Simek** [comment]
@asklar Expected, you should use canonical link:
* https://raw.githubusercontent.com/asklar/react-native-xaml/main/example/rnx.gif
