### ISSUE TITLE
react-native-video-processing expo support

### ISSUE THREAD

**Issue by tuncpolat** [react-native-community/directory#628]
Trying to use this library to compress video on upload. Can't see video compressing opportunities in expo.

**Comment by luism3861** [comment]
hi @tuncpolat  try to open a issue in this library repo!.

**Comment by Simek** [comment]
Hi @tuncpolat , at first, I thought it's an invalid platform added to the library in RN Directory, but it looks like, it only includes Android and iOS as supported platforms:
<img width="401" alt="Screenshot 2021-04-27 161538" src="https://user-images.githubusercontent.com/719641/116257074-03661a00-a774-11eb-86e0-1628aa38ab4d.png">

As the comment above says, please report the issue in the library repository, we have no control over which library supports which platforms. 😉
