### ISSUE TITLE
Add windows compatibility

### ISSUE THREAD

**Issue by dantman** [react-native-community/directory#66]
[react-native-windows](https://github.com/Microsoft/react-native-windows) is a 3rd party library that adds "windows" (Windows 10, Mobile, Xbox/UWP) as a react-native platform.

A portion of react-native libraries with android/ios code have added support for react-native-windows by adding native windows code as well. It would probably be good to add a `"windows": bool` flag in addition to the android and ios flags.

**Comment by jimmylee** [comment]
This is an awesome idea :) I will get to it.

**Comment by jonsamp** [comment]
This PR adds support for windows: https://github.com/react-native-community/directory/pull/232

Closing this issue!
