### ISSUE TITLE
separate count-buttons from project img

### ISSUE THREAD

**Issue by rohozhnikoff** [react-native-community/directory#7]
heyhey, nice start

some of repos have this buttons, which is more "statuses" then "img shown what pkg do"
<img width="1212" alt="screen shot 2017-07-11 at 10 44 14" src="https://user-images.githubusercontent.com/1474534/28056640-365f09a0-6626-11e7-80c6-9a8415a6b349.png">
will be better to group them by camo.githubusercontent.com (and exclude from main list) and show in separate view

**Comment by jimmylee** [comment]
@rohozhnikoff great suggestion!! We'll do this :D

**Comment by jonsamp** [comment]
We no longer show images on the directory (after the redesign). In the future we may add this feature back, but for now I'm going to close this issue.
