### ISSUE TITLE
Site isn't being updated

### ISSUE THREAD

**Issue by yfunk** [react-native-community/directory#787]
It seems like the site hasn't been deployed / updated since almost a week ago:

- Changes in the latest commit (a2d98ad) on `master` aren't visible in the live version
- The `stats` for each library have last been updated 6 days ago (best visible when [sorting by "Last Updated"](https://reactnative.directory/?order=updated))

According to the `README` this should be happening automatically, so I assume that there's an issue on the hosting side.

(cc @Simek)

**Comment by Simek** [comment]
Thanks for the report! 👍 I have just deployed the PR which should fix the issue.
