### ISSUE TITLE
Images may get clipped when the lib is the last on the page

### ISSUE THREAD

**Issue by SrBrahma** [react-native-community/directory#792]
Example:

![image](https://user-images.githubusercontent.com/28177550/154590987-e98d50c7-192a-440c-9af9-f174cf21d519.png)

The image is taller but can't be shown as it's out of page bounds

**Comment by Simek** [comment]
Hello @SrBrahma, thank you for the report! 👍 

For now, the issue should be fixed (in most of the cases) via the mentioned PR. We will investigate how to improve whole thumbnails/gallery feature in the future.
