### ISSUE TITLE
libp2p not compatible with react native expo 

### ISSUE THREAD

**Issue by PranavAggarwal471** [react-native-community/directory#862]
Please add libp2p library module and make it compatoble with the expo cli and expo go in react native.

**Comment by Simek** [comment]
Hello @PranavAggarwal471, in the Directory, we only gather the public information and display it in a form of registry.

If you want to ask for the for the feature or change, you probably should create issue or fill the feature request in the library repository (which is `libp2p` in your case - https://github.com/libp2p).
