### ISSUE TITLE
Genius Scan SDK Compability

### ISSUE THREAD

**Issue by iorran** [react-native-community/directory#993]
Link: 

https://geniusscansdk.com/

https://www.npmjs.com/package/@thegrizzlylabs/react-native-genius-scan

Hi guys, I would like to know if its possible to use expo with this library above.

**Comment by Simek** [comment]
Hello @iorran, you can currently use any Rect Native library with Expo.

For this one you will need to add `expo-dev-client` to your project (https://docs.expo.dev/develop/development-builds/introduction). The only limitation is that the library cannot be used with Expo Go/Snack.
