### ISSUE TITLE
jsonform / react-jsonschema-form (Dynamic Forms from JSON Schema)

### ISSUE THREAD

**Issue by Nezteb** [react-native-community/directory#998]
I've got a project with a Postgres table with a JSONB column. In this column, there is a JSON Schema for an item/asset/widget. I want to dynamically generate React Native forms for these JSON Schema.

Libraries that do this:
- https://github.com/jsonform/jsonform
- https://github.com/rjsf-team/react-jsonschema-form

Looking at Expo's package compatibility docs: https://docs.expo.dev/workflow/using-libraries/#determining-third-party-library-compatibility

> **Now check the following:**
> 
> - **Does it include an ios and/or android/ directory?**
>    - _No._
> - **Does the README mention linking?**
>    - _No._
> - **Is it built specifically for Node.js, the web, electron, or another platform?**
>    - _Unsure?_
>        - _`jsonform` says "The JSON Form library is a JavaScript client-side library..."._
>        - _`react-jsonschema-form` says "A simple React component capable of building HTML forms..."._

I checked the React Native directory and couldn't find anything: https://reactnative.directory/?expo=true&search=json

**Comment by Simek** [comment]
Hello @Nezteb, let's start from the beginning. In general, React libraries cannot be used directly with React Native. 

The Expo docs you refer to explains how to check if React Native package is compatible with Expo Go (this is also what's the label in the directory means). Every React Native library can be used with Expo leveraging Dev Client feature - https://docs.expo.dev/develop/development-builds/introduction/.

ATM, in directory, we do not have listed any React Native library which could help achieve what you want to, but I was able to find a project on GitHub which might help you:
* https://github.com/CareLuLu/react-native-web-jsonschema-form

Will also add it to the directory listing soon.
